name: phishnclick-prod

services:
  backend:
    image: nguyenthaohan214/phishnclick-backend:latest
    env_file:
      - backend.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - phishnclick-net

  frontend:
    image: nguyenthaohan214/phishnclick-frontend:latest
    env_file:
      - frontend.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - phishnclick-net

networks:
  phishnclick-net:
    driver: bridge
